eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2-databases/vaadin-microservices-demo-db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: username
    password: password
