eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 6000
  ReadTimeout: 3000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

feign.hystrix.enabled: true

biz-application.name: biz-application
