endpoints.health.enabled: true

ribbon:
  serverListRefreshInterval: 5000
  ConnectTimeout: 6000
  ReadTimeout: 5000

hystrix.command.default.execution.isolation:
    thread.timeoutInMilliseconds: 10000
    strategy: THREAD

feign.hystrix.enabled: true

hazelcast.max.no.heartbeat.seconds: 10

biz-application.name: biz-application
