management.endpoints.web.exposure.include: "*"

hazelcast.max.no.heartbeat.seconds: 6

admin-application.url: http://192.168.1.150:8080/admin/ui/

news-application.url: http://192.168.1.150:8080/news/ui/
